[colors]
bg = #cc1e222a
fg = #abb2bf
green = #98c379
red = #e06c75
yellow = #e5c07b
blue = #61afef

[bar/main]
width = 100%
height = 30
; Transparencia aplicada mediante el canal alfa del color
background = ${colors.bg}
foreground = ${colors.fg}
font-0 = "JetBrainsMono Nerd Font:size=10;3"
padding = 2
module-margin = 1

; Módulos configurados
modules-left = xworkspaces
modules-center = date
modules-right = cpu ram pulseaudio wlan battery tray bluetooth

[module/tray]
type = internal/tray
tray-spacing = 8px
tray-size = 60%
tray-background = ${colors.bg}

[module/xworkspaces]
type = internal/xworkspaces
label-active = "  "
label-active-foreground = ${colors.green}
label-active-background = ${colors.bg}
label-occupied = "  "
label-occupied-foreground = #888888
label-empty = "  "
label-empty-foreground = #444444
label-active-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

[module/cpu]
type = internal/cpu
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.green}
label = %percentage%%

[module/ram]
type = internal/memory
format = <label>
format-prefix = "󰘾 "
format-prefix-foreground = ${colors.green}
label = %gb_used%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.green}
label-volume = %percentage%%

[module/wlan]
type = internal/network
interface-type = wireless
label-connected = " "
label-disconnected = "󰖪 "
label-connected-foreground = ${colors.green}

[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = AC
label-charging = 󰂄 %percentage%%
label-discharging = 󰁹 %percentage%%
label-full = 󰁹 100%

[module/date]
type = internal/date
date = %H:%M
label = %date%
label-foreground = ${colors.fg}

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 2
; Usamos dbus-launch para que la ventana tenga su propio bus privado y no dependa del applet
click-left = dbus-launch blueman-manager &
format-foreground = ${colors.blue}
format-padding = 1
